CREATE TABLE IF NOT EXISTS students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    lastName TEXT NOT NULL CHECK(length(lastName) <= 50),
    firstName TEXT NOT NULL CHECK(length(firstName) <= 50),
    school VARCHAR(100) NOT NULL,
    age INTEGER NOT NULL CHECK(age > 0),
    PRIMARY KEY(ID)
);

INSERT INTO students (id, lastname, firstname, school, age) VALUES (1, 'Brown', 'Marvin', 'First', 15);
