spring.application.name=rest_application
spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=user
spring.datasource.password=pass

spring.sql.init.mode=always

logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.data=DEBUG
